### ISSUE TITLE
Fullscreen and other APIs

### ISSUE THREAD

**Issue by annevk** [WICG/capability-delegation#10]
The specification talks about fullscreen, but it seems only payments is supported? Why is that?

**Comment by mustaqahmed** [comment]
Yes, adding a monkey-patch for fullscreen spec sounds great, thanks.

We wanted to start simple until we have consensus on the generic delegation API, so we narrowed down on the immediate use-case we want to support.  Do you think we should wait for an initial [TAG review](https://github.com/w3ctag/design-reviews/issues/655)?  Or adding a fullscreen spec patch now would be better for their review too?

**Comment by annevk** [comment]
As long as you make it clear it's part of the plan it probably doesn't matter.

**Comment by michaelwasserman** [comment]
A github.com/webscreens/window-placement partner asked for functionality that would be made possible by supporting fullscreen delegation. Their use case is that a page opens a popup with UI and accelerators that users interact with to request fullscreen on the opener (or move the already-fullscreen opener from one screen to another via new multi-screen window placement features) . See additional details in crbug.com/1293083

**Comment by mustaqahmed** [comment]
WPTs for this PR was added through https://github.com/web-platform-tests/wpt/pull/34004.
