### ISSUE TITLE
Delegating a capability not acquired yet.

### ISSUE THREAD

**Issue by ArthurSonzogni** [WICG/capability-delegation#3]
By providing the capability delegation as a string, developers may delegate features they don't have access to yet.

For instance. What would happen if:
```javascript
postMessage("msg", {delegate: "geolocalisation"});
```
is sent before asking the users to allow geolocalisation on the document?

One alternative would have been to pass some "Capability/Token" object that can be constructed after getting access to a feature. This way, you could only delegate capabilities you already have access to.

If strings are used this bring interesting questions:
1. Do delegations applies retroactively to user's permission prompt? 
2. If the permission prompt happens after the delegation, where do you show permission prompt? On both windows?
3. Do you have race conditions? How do the specification deals with it?

+CC @MikeWest

**Comment by mustaqahmed** [comment]
FYI @clelland: This is related to the first point #4.

Can we perhaps just fail the delegation if the sender doesn't already have the corresponding Permissions Policy enabled?

**Comment by andypaicu** [comment]
> FYI @clelland: This is related to the first point #4.
> 
> Can we perhaps just fail the delegation if the sender doesn't already have the corresponding Permissions Policy enabled?

I think this would be a good restriction otherwise the implementation of permission prompts for capabilities that are gated by them would likely be confusing or impossible. And it should not impede use cases as the top-level frame can always query the permission before, or even respond to the message post failing because of it.

**Comment by andypaicu** [comment]
@clelland @mustaqahmed has there been any update on this issue? I think it's really important to ensure that capabilities can only be delegated if the prerequisites for using said capability are already met by the delegator. Otherwise it will be difficult to e.g. present permission prompts, from a user design perspective.

**Comment by mustaqahmed** [comment]
Does it sound reasonable if we throw a ["NotAllowedError"](https://heycam.github.io/webidl/#notallowederror) DOMException as the very first sub-step in Step 8 of [our modified algorithm for window post message](https://wicg.github.io/capability-delegation/spec.html#monkey-patch-to-html-initiating-delegation)?

**Comment by mustaqahmed** [comment]
> .. can only be delegated if the prerequisites ... are already met by the delegator.

@andypaicu In Permissions terminology, you meant allowing delegation only when `PermissionStatus.state == "granted"`, am I correct?

**Comment by andypaicu** [comment]
> > .. can only be delegated if the prerequisites ... are already met by the delegator.
> 
> @andypaicu In Permissions terminology, you meant allowing delegation only when `PermissionStatus.state == "granted"`, am I correct?

Indeed that is what I mean. Apologies for the delay the reply slipped through the cracks.

**Comment by clelland** [comment]
(This just rose to the top of my inbox backlog; sorry for the very long delay there)

The proposal in https://github.com/WICG/capability-delegation/issues/3#issuecomment-878395483 makes sense; blocking the delegation when it wouldn't be allowed by permissions policy (not 'allowed to use', in HTML parlance) sounds like a good idea.

**Comment by mustaqahmed** [comment]
I am finally looking into integrating permission state in my proposed monkey-patches.

@clelland Not sure how to specify a capability when checking `PermissionStatus.state == "blah"`.  Do you know any other spec algorithm that can guide me?
