### ISSUE TITLE
Interaction with Permissions / Feature Policy

### ISSUE THREAD

**Issue by rowan-m** [WICG/capability-delegation#4]
How does this interact with Permissions Policy. e.g. in the example and demo shown:

```js
checkout_button.onclick = () => {
    targetWindow.postMessage("process_payment", {delegate: "payment"});
};
```

The top-level frame knows the origin of `targetWindow` so it seems reasonable that it might have set a Permissions Policy to enable or restrict the feature for that origin. As in, it feels like a site might want to prevent the ability for a malicious script to insert an entry like this to delegate a capability.

Likewise, though this might just be my own confusion / wish-list, it would be nice if the capabilities were consistent in naming with Permissions Policy too… but I don't know if that's a valid thing to want.

**Comment by mustaqahmed** [comment]
Re your first point (how Permissions Policy could affect capability delegation): This is a very good point, we haven't looked into this yet.  I think requiring access to the capability from both sender and receiver `Window`s would a good solution.  What do you think?  

Re your second point (naming of a capability): we used the exact same names like Permissions Policy in our draft spec [Section 3](https://wicg.github.io/capability-delegation/spec.html#initiating-delegation) (see "feature-identifier").  Please comment if we need to do more.

FYI @clelland who already helped us with naming: please let us know your thoughts about the first point.  Do you see any complications with my suggestion?

**Comment by clelland** [comment]
The `Permissions-Policy` header is used to specify the origins which could potentially be granted permission to use a feature; it's implicitly '*' for each feature, but can be restricted arbitrarily, even blocking the feature in the document which set the header, if that's desired.

I could imagine that this would work with Capability Delegation similarly; that by default, capabilities could be delegated to any origin, but if a header like

    Permissions-Policy: some-capability-identifier=(self "https://a.example" "https://b.example")

were received, then that capability could only be delegated to pages on those origins. (In exactly the same way that the `<iframe allow>` attribute can only be used to grant permissions to pages on those origins)

**Comment by mustaqahmed** [comment]
@rowan-m: capability names are consistent with Permissions, see [this section](https://wicg.github.io/capability-delegation/spec.html#initiating-delegation) of our spec proposal.

As for your first point (interaction with Permissions), let's continue the discussion in #3.  Closing this issue now.
